# Build stage
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Copy the project file and restore dependencies
COPY TagFlowApi/TagFlowApi.csproj TagFlowApi/
RUN dotnet restore "TagFlowApi/TagFlowApi.csproj"

# Copy the rest of the code
COPY . .

# Set the working directory to the folder containing the .csproj file
WORKDIR "/src/TagFlowApi"
RUN dotnet publish "TagFlowApi.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

# Copy the published files from the build stage
COPY --from=build /app/publish .

# Set the entry point to run the app
ENTRYPOINT ["dotnet", "TagFlowApi.dll"]
