app = "tagflowprobackend"  # Replace with your app's name

[build]
  dockerfile = "./Dockerfile" 

[[services]]
  internal_port = 80
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
